--liquibase formatted sql
--changeset sagar:3

INSERT INTO krew_actn_itm_t (ACTN_ITM_ID, PRNCPL_ID, ASND_DT, RQST_CD, ACTN_RQST_ID, DOC_HDR_ID, ROLE_NM, DLGN_PRNCPL_ID, DOC_HDR_TTL, DOC_TYP_LBL, DOC_HDLR_URL, DOC_TYP_NM, RSP_ID, DLGN_TYP, VER_NBR, DTYPE, GRP_ID, DLGN_GRP_ID, RQST_LBL) VALUES('aid5', 'pid5', '2018-01-13 23:54:11', 'n', 'arid5', 'dhid5', 'rider', 'dlgnpid5', 'github', 'passport', 'www.google.com', '100', 'rspid5', 'f', 0, 'passport', 'a5', 'grp5', 'rqst5');
INSERT INTO krew_actn_itm_t (ACTN_ITM_ID, PRNCPL_ID, ASND_DT, RQST_CD, ACTN_RQST_ID, DOC_HDR_ID, ROLE_NM, DLGN_PRNCPL_ID, DOC_HDR_TTL, DOC_TYP_LBL, DOC_HDLR_URL, DOC_TYP_NM, RSP_ID, DLGN_TYP, VER_NBR, DTYPE, GRP_ID, DLGN_GRP_ID, RQST_LBL) VALUES('aid6', 'pid6', '2018-07-23 17:05:11', 'y', 'arid6', 'dhid6', 'driver', 'dlgnpid6', 'orkut', 'pancard', 'www.iu.edu', '120', 'rspid6', 'h', 0, 'pancard', 'a6', 'grp6', 'rqst6');
INSERT INTO krew_actn_itm_t (ACTN_ITM_ID, PRNCPL_ID, ASND_DT, RQST_CD, ACTN_RQST_ID, DOC_HDR_ID, ROLE_NM, DLGN_PRNCPL_ID, DOC_HDR_TTL, DOC_TYP_LBL, DOC_HDLR_URL, DOC_TYP_NM, RSP_ID, DLGN_TYP, VER_NBR, DTYPE, GRP_ID, DLGN_GRP_ID, RQST_LBL) VALUES('aid7', 'pid7', '2018-03-05 03:14:01', 'y', 'arid7', 'dhid7', 'applier', 'dlgnpid7', 'linkedin', 'license', 'www.linkedin.com', '140', 'rspid6', 'i', 0, 'license', 'a7', 'grp7', 'rqst7');
INSERT INTO krew_actn_itm_t (ACTN_ITM_ID, PRNCPL_ID, ASND_DT, RQST_CD, ACTN_RQST_ID, DOC_HDR_ID, ROLE_NM, DLGN_PRNCPL_ID, DOC_HDR_TTL, DOC_TYP_LBL, DOC_HDLR_URL, DOC_TYP_NM, RSP_ID, DLGN_TYP, VER_NBR, DTYPE, GRP_ID, DLGN_GRP_ID, RQST_LBL) VALUES('aid8', 'pid8', '2017-12-29 13:07:25', 'y', 'arid8', 'dhid8', 'coder', 'dlgnpid8', 'indeed', 'crimson card', 'www.indeed.com', '160', 'rspid8', 'j', 0, 'crimson card', 'a8', 'grp8', 'rqst8');
INSERT INTO krew_actn_itm_t (ACTN_ITM_ID, PRNCPL_ID, ASND_DT, RQST_CD, ACTN_RQST_ID, DOC_HDR_ID, ROLE_NM, DLGN_PRNCPL_ID, DOC_HDR_TTL, DOC_TYP_LBL, DOC_HDLR_URL, DOC_TYP_NM, RSP_ID, DLGN_TYP, VER_NBR, DTYPE, GRP_ID, DLGN_GRP_ID, RQST_LBL) VALUES('aid9', 'pid9', '2017-10-02 19:23:18', 'y', 'arid9', 'dhid9', 'manager', 'dlgnpid9', 'chegg', 'wallet', 'www.gmail.com', '180', 'rspid9', 'k', 0, 'wallet', 'a9', 'grp9', 'rqst9');
INSERT INTO krew_actn_itm_t (ACTN_ITM_ID, PRNCPL_ID, ASND_DT, RQST_CD, ACTN_RQST_ID, DOC_HDR_ID, ROLE_NM, DLGN_PRNCPL_ID, DOC_HDR_TTL, DOC_TYP_LBL, DOC_HDLR_URL, DOC_TYP_NM, RSP_ID, DLGN_TYP, VER_NBR, DTYPE, GRP_ID, DLGN_GRP_ID, RQST_LBL) VALUES('aid10', 'pid10', '2017-11-25 20:34:57', 'y', 'arid10', 'dhid10', 'assistant', 'dlgnpid10', 'travis', 'credit card', 'www.twitter.com', '200', 'rspid10', 'l', 0, 'credit card', 'a10', 'grp10', 'rqst10');
INSERT INTO krew_actn_itm_t (ACTN_ITM_ID, PRNCPL_ID, ASND_DT, RQST_CD, ACTN_RQST_ID, DOC_HDR_ID, ROLE_NM, DLGN_PRNCPL_ID, DOC_HDR_TTL, DOC_TYP_LBL, DOC_HDLR_URL, DOC_TYP_NM, RSP_ID, DLGN_TYP, VER_NBR, DTYPE, GRP_ID, DLGN_GRP_ID, RQST_LBL) VALUES('aid11', 'pid11', '2017-10-15 10:42:43', 'n', 'arid11', 'dhid11', 'professor', 'dlgnpid11', 'code climate', 'aadhar', 'www.nokia.com', '220', 'rspid11', 'p', 0, 'aadhar', 'a11', 'grp11', 'rqst11');
INSERT INTO krew_actn_itm_t (ACTN_ITM_ID, PRNCPL_ID, ASND_DT, RQST_CD, ACTN_RQST_ID, DOC_HDR_ID, ROLE_NM, DLGN_PRNCPL_ID, DOC_HDR_TTL, DOC_TYP_LBL, DOC_HDLR_URL, DOC_TYP_NM, RSP_ID, DLGN_TYP, VER_NBR, DTYPE, GRP_ID, DLGN_GRP_ID, RQST_LBL) VALUES('aid12', 'pid12', '2017-09-14 22:14:25', 'y', 'arid12', 'dhid12', 'student', 'dlgnpid12', 'slack', 'meal card', 'www.wwf.com', '240', 'rspid12', 's', 0, 'meal card', 'a12', 'grp12', 'rqst12');
INSERT INTO krew_actn_itm_t (ACTN_ITM_ID, PRNCPL_ID, ASND_DT, RQST_CD, ACTN_RQST_ID, DOC_HDR_ID, ROLE_NM, DLGN_PRNCPL_ID, DOC_HDR_TTL, DOC_TYP_LBL, DOC_HDLR_URL, DOC_TYP_NM, RSP_ID, DLGN_TYP, VER_NBR, DTYPE, GRP_ID, DLGN_GRP_ID, RQST_LBL) VALUES('aid13', 'pid13', '2017-05-27 00:34:55', 'n', 'arid13', 'dhid13', 'dean', 'dlgnpid13', 'jacoco', 'voterID', 'www.duckduckgo.com', '260', 'rspid13', 'u', 0, 'voterID', 'a13', 'grp13', 'rqst13');
INSERT INTO krew_actn_itm_t (ACTN_ITM_ID, PRNCPL_ID, ASND_DT, RQST_CD, ACTN_RQST_ID, DOC_HDR_ID, ROLE_NM, DLGN_PRNCPL_ID, DOC_HDR_TTL, DOC_TYP_LBL, DOC_HDLR_URL, DOC_TYP_NM, RSP_ID, DLGN_TYP, VER_NBR, DTYPE, GRP_ID, DLGN_GRP_ID, RQST_LBL) VALUES('aid14', 'pid14', '2017-03-25 10:24:32', 'y', 'arid14', 'dhid14', 'principal', 'dlgnpid14', 'postman', 'school card', 'www.firefox.com', '280', 'rspid14', 'z', 0, 'school card', 'a14', 'grp14', 'rqst14');
INSERT INTO krew_actn_itm_t (ACTN_ITM_ID, PRNCPL_ID, ASND_DT, RQST_CD, ACTN_RQST_ID, DOC_HDR_ID, ROLE_NM, DLGN_PRNCPL_ID, DOC_HDR_TTL, DOC_TYP_LBL, DOC_HDLR_URL, DOC_TYP_NM, RSP_ID, DLGN_TYP, VER_NBR, DTYPE, GRP_ID, DLGN_GRP_ID, RQST_LBL) VALUES('aid15', 'pid15', '2017-07-15 20:34:57', 'n', 'arid15', 'dhid15', 'director', 'dlgnpid15', 'whatsapp', 'chip card', 'www.chrome.com', '300', 'rspid15', 'j', 0, 'chip card', 'a15', 'grp15', 'rqst15');
